
services:
#  app:
#    image:  notes-api
#    build:
#      context: .
#      dockerfile: Dockerfile
#    ports:
#      - "8080:8080"

  db:
    image: postgres
    environment:
      POSTGRES_DB: notes
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5051:80"


